import { useCallback, useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { isOnMuhu, distanceMeters } from "@/lib/muhu";
import * as api from "@/lib/firebase-data";
export type Position = { lat: number; lng: number };
export function useGeolocation(active: boolean) { const [pos,setPos]=useState<Position|null>(null); const [error,setError]=useState<string|null>(null); useEffect(()=>{ if(!active||typeof window==="undefined")return; let cancelled=false; let clear:(()=>void)|null=null; (async()=>{try{const {Geolocation}=await import("@capacitor/geolocation"); await Geolocation.requestPermissions().catch(()=>undefined); const id=await Geolocation.watchPosition({enableHighAccuracy:true,timeout:20000,maximumAge:5000},(p,e)=>{if(cancelled)return;if(e||!p){setError(e?.message??"Asukohta ei saa");return}setPos({lat:p.coords.latitude,lng:p.coords.longitude});setError(null)});if(cancelled)void Geolocation.clearWatch({id});else clear=()=>void Geolocation.clearWatch({id});}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"Asukohta ei saa")}})();return()=>{cancelled=true;clear?.()};},[active]); return {pos,error,onMuhu:pos?isOnMuhu(pos.lat,pos.lng):false}; }
export function useMuhuData(_code:string|null, groupId:string|null){const pointsQuery=useQuery({queryKey:["points",groupId],enabled:!!groupId,queryFn:()=>api.listFirebasePoints(groupId!)});const tracksQuery=useQuery({queryKey:["tracks"],enabled:!!_code,queryFn:api.listFirebaseTracks});return {pointsQuery,tracksQuery};}
export function useTracking(code:string|null,pos:Position|null){const qc=useQueryClient();const [trackId,setTrackId]=useState<string|null>(null);const [liveTrack,setLiveTrack]=useState<[number,number][]>([]);const buffer=useRef<{lat:number;lng:number;t:string}[]>([]);const last=useRef<Position|null>(null);useEffect(()=>{if(!trackId||!pos||!code)return;if(last.current&&distanceMeters(last.current,pos)<8)return;last.current=pos;buffer.current.push({...pos,t:new Date().toISOString()});setLiveTrack(p=>[...p,[pos.lat,pos.lng]])},[pos,trackId,code]);useEffect(()=>{if(!trackId)return;const flush=async()=>{const b=buffer.current;if(!b.length)return;buffer.current=[];try{await api.appendFirebaseTrackPoints(trackId,b)}catch{buffer.current=[...b,...buffer.current]}};const timer=setInterval(flush,15000);return()=>{clearInterval(timer);void flush()}},[trackId]);const start=useCallback(async()=>{if(!code)return;setTrackId(await api.startFirebaseTrack());last.current=null;setLiveTrack([]);toast.success("Jälgimine käib")},[code]);const stop=useCallback(async()=>{if(!trackId)return;const b=buffer.current;buffer.current=[];if(b.length)await api.appendFirebaseTrackPoints(trackId,b);await api.endFirebaseTrack(trackId);setTrackId(null);setLiveTrack([]);void qc.invalidateQueries({queryKey:["tracks"]});toast.success("Jälgimine lõpetatud")},[trackId,qc]);return {tracking:!!trackId,liveTrack,start,stop};}
export function usePointActions(_code:string|null,groupId:string|null){const qc=useQueryClient();const invalidate=()=>void qc.invalidateQueries({queryKey:["points",groupId]});const add=useMutation({mutationFn:(i:{title:string;lat:number;lng:number})=>api.addFirebasePoint(groupId!,i.title,i.lat,i.lng,"Kasutaja"),onSuccess:()=>{invalidate();toast.success("Punkt lisatud")},onError:(e:Error)=>toast.error(e.message)});const remove=useMutation({mutationFn:api.deleteFirebasePoint,onSuccess:()=>{invalidate();toast.success("Punkt kustutatud")}});const setVisited=useMutation({mutationFn:(i:{id:string;visited:boolean})=>api.toggleFirebaseVisit(i.id,i.visited),onSuccess:(_,i)=>{invalidate();toast.success(i.visited?"Märgitud käiduks":"Käidud märge eemaldatud")}});const update=useMutation({mutationFn:(i:{id:string;title?:string;description?:string})=>api.updateFirebasePoint(i.id,{title:i.title,description:i.description}),onSuccess:()=>{invalidate();toast.success("Salvestatud")}});return {add,remove,setVisited,update};}
